---

ansible_ssh_user              : ubuntu
ansible_ssh_private_key_file  : /home/aronov/.ssh/Mongo_Cluster.pem
mongodb_primary: "{{ hostvars[groups['mongo_master'][0]].ansible_default_ipv4.address }}"
mongodb_secondary_1: "{{ hostvars[groups['mongo_replicas'][0]].ansible_default_ipv4.address }}"
mongodb_secondary_2: "{{ hostvars[groups['mongo_replicas'][1]].ansible_default_ipv4.address }}"

ansible_python_interpreter    : /usr/bin/python3
