---
# tasks file for mongodb

- name: Import the public key
  shell:
    wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -

- name: Create a list file for MongoDB
  shell:
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list


- name: Update repositories cache and install "MongoDB" package
  become: yes
  apt:
    name: mongodb-org
    update_cache: yes

- name: Service mongod is running
  become: yes
  systemd:
    state: started
    enabled: yes
    name: mongod
