---

- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Gathering Facts
      setup:

- hosts: mongo
  gather_facts: yes
  roles:
    - role: mongodb
      when: "'mongo_master' in group_names"

- hosts: mongo
  gather_facts: yes
  roles:
    - role: mongodb
      when: "'mongo_replicas' in group_names"
