---

- hosts: all
  become: true
  gather_facts: yes
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Gathering Facts
      setup:

- hosts: mongo
  roles:
    - role: mongodb

- hosts: mongo_master
  roles:
    - role: replicaset

- hosts: mongo_replicas
  roles:
    - role: replicaset
