---
# defaults file for mongodb
mongodb_replication_replset: rp0                  # Enable replication <setname>[/<optionalseedhostlist>]
mongodb_security_authorization: "enabled"
mongodb_primary: "{{ hostvars[groups['mongo_master'][0]].ansible_default_ipv4.address }}"
mongodb_secondary_1: "{{ hostvars[groups['mongo_replicas'][0]].ansible_default_ipv4.address }}"
mongodb_secondary_2: "{{ hostvars[groups['mongo_replicas'][1]].ansible_default_ipv4.address }}"
